V8 - add ruamel.yaml==0.16.10, altair==3.3.0 to marvin-requirements.txt
kwhanalytics/data-env pull request #14
Opened 2020-09-09 20:48 UTC by cscanlin-kwh

2020-09-30 21:17 UTC, kelliott-kwh approved these changes

2020-09-30 21:18 UTC, kelliott-kwh requested changes
Where's altair==3.3.0?

2020-09-30 22:40 UTC, shutton-kwh approved these changes

2020-09-30 22:45 UTC, cscanlin-kwh commented
> Where's altair==3.3.0?

Good catch, it got missed in the last cherry-pick. Added now.

2020-09-30 23:56 UTC, kelliott-kwh approved these changes

2020-10-01 00:03 UTC, shutton-kwh commented on marvin-requirements.txt
> +altair==3.3.0
Weird, how was our code working without altair in the venv?

2020-10-01 00:10 UTC, merged